### ISSUE TITLE
Bad breath not respawning

### ISSUE THREAD

**Issue by SighDuck265** [mcfullard/ttd-release#1] opened 2015-10-18 13:25 UTC
Title is pretty self explanatory. The bad breath enemies do not respawn after they have been killed.

**Comment by mcfullard** [comment] 2015-10-18 13:33
Hi SighDuck265. Thank you for logging an issue, we really appreciate it. This is not a bug, but rather planned behaviour. We'll definitely take your comment into consideration when planning the next release.

**Comment by mcfullard** [comment] 2015-10-18 13:34
I'll actually leave this issue open so that my fellow developers can chip in and add their opinions before we decide to change the behaviour. @RhysBotes , @fubar42 , @Bas24live please consider this

**Comment by Bas24live** [comment] 2015-10-18 13:37
We initially decided on it being that way, but we might change it in a later release in order to make the game more difficult. Perhaps even only make them respawn once you reach a certain level or something along those lines.

**Comment by mcfullard** [comment] 2015-10-18 19:44
I think we can agree that this is a wontfix for now.

**Closed as completed by mcfullard** 2015-10-18 19:44 UTC
Labels: wontfix
